backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      slug: "{{slug}}"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Links'
          name: "links"
          widget: list
          fields:
            - { label: "Name", name: "label", widget: "string"}
            - { label: "URL", name: "href", widget: "text"}
